name: 'Hello Action'
description: 'A custom GitHub Action that greets the user'
inputs:
  who-to-greet:
    description: 'The name to greet'
    required: true
outputs:
  greeting:
    description: 'The greeting message'
runs:
  using: 'docker'
  image: 'Dockerfile'
